{"name": "Тест получения заказов пользователем без авторизации", "status": "passed", "description": "Проверка ошибки при попытке получения списка заказов пользователем без авторизации. Ожидается статус 401 и сообщение об ошибке.", "start": 1700764884665, "stop": 1700764885010, "uuid": "9d1ea481-df41-419a-956e-a27dd7dada94", "historyId": "40478a1e9f278e2fa532f2100ecc82e0", "testCaseId": "40478a1e9f278e2fa532f2100ecc82e0", "fullName": "tests.test_user_orders.TestUserOrders#test_get_orders_without_auth_user_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_orders"}, {"name": "subSuite", "value": "TestUserOrders"}, {"name": "host", "value": "LAPTOP-U8DEQNJF"}, {"name": "thread", "value": "22668-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_orders"}]}