{"name": "Тест создания существующего пользователя", "status": "passed", "description": "Проверка ошибки при попытке создания уже существующего пользователя. Ожидается получение статуса 403 и соответствующего сообщения об ошибке.", "start": 1700764878646, "stop": 1700764879362, "uuid": "1cd7e5dd-386a-435a-8b60-a7f9ed249e0d", "historyId": "bc8c7b320dae1bf802b388fe6f880dc0", "testCaseId": "bc8c7b320dae1bf802b388fe6f880dc0", "fullName": "tests.test_user_creation.TestUserCreation#test_create_existing_user_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_creation"}, {"name": "subSuite", "value": "TestUserCreation"}, {"name": "host", "value": "LAPTOP-U8DEQNJF"}, {"name": "thread", "value": "22668-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_creation"}]}